### ISSUE TITLE
Not working and features

### ISSUE THREAD

**Issue by aemonge** [tumpio/toolbarpositionchanger#1]
Hi, i've just installed this because the bottom UI you said it was deprecated. 

I'm no OSx with firefox 42. but it doesn't make anything on the bottom. Ideally i would like to have just the tabs on the bottom,

Cheers

**Comment by aemonge** [comment]
Sorry I didn't realize you had to open the customize q=

**Comment by tumpio** [comment]
Hi, you can keep using Bottom UI if it provides the functionality you need. The Toolbar Position Changer provides user control over which toolbars are moved on the bottom and in which order.

In technical aspect TPC is more complex as it really moves the toolbars under a new container instead of just displaying UI elements in different order what Bottom UI does. Because Firefox has not been designed to have "position free" toolbars, some features like toolbar hiding required some patching.

Although Bottom UI is now deprecated,  it does not mean that it has stopped from working. I'm just focusing on TPC since with it you can achieve all what Bottom UI has to offer.

**Comment by tumpio** [comment]
Also If you find bugs while using it on OSx, please report. It has not been tested on it, since I do not have one to test with :)

**Comment by aemonge** [comment]
Sure !!! If any bugs I found I'll tell you, always happy to help !!!!

[btw. If it was my choice I would be using arch-linux ]
