### ISSUE TITLE
Support to full-screen plugin

### ISSUE THREAD

**Issue by aemonge** [tumpio/toolbarpositionchanger#2]
Hi !!!

In OsX, meaning of fullscreen have changed..... so there's a need for this plug-in https://github.com/alex-pl/full-fullscreen . Can you support it ? Since when I've got my tabbar on the bottom, it doesn't hides when toggling fullscreen. I've raise an issue in the other repo as well. 
https://github.com/alex-pl/full-fullscreen/issues/1

In advance, thank you SO very much
Cheers

**Comment by tumpio** [comment]
Hi,

so how does the fullscreen work on OsX? What kind of fullscreen is it if the toolbars are not hiding? But I'll see what I can do to it.

**Comment by aemonge** [comment]
Soon I'll be having vacations, so I can try to help you as well.   Hmmmmm, i know men OsX sucks, or we totally don't get it /:

**Comment by tumpio** [comment]
The bug related to this is open at Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=740148

In my opinion this should be fixed by Mozilla.

These two addons were also mentioned in that bug report:
https://addons.mozilla.org/en-US/firefox/addon/nofs/
https://addons.mozilla.org/en-us/firefox/addon/old-lion-fullscreen/

Can you test above addons if they work any differently with my addon?
